future: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    span:
      line_numbers: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      back_link: "/blog"
